### PR TITLE
Update for Thunderbird 68.0

### PR DESCRIPTION
**Pull request by bit**

### CODE REVIEW

**Comment by designchris** [comment]
Does anyone know what needs to be done to support TB68?

**Comment by leres** [comment]
I wrote a python script to convert install.rdf files to manifest.json:

    [https://github.com/leres/mozilla-install-rdf-to-manifest-json](https://github.com/leres/mozilla-install-rdf-to-manifest-json)

And the manifest.json I've been using for the last few weeks is a little different from the one in [pull request #10](https://github.com/dennisverspuij/tb-correctidentity/pull/10/commits/f3255a1ba441b15e552c53f6997980af15da8394).

**Comment by designchris** [comment]
@leres Thanks, I tried to run your script but it's throwing an error:
 
>  File "./convert-rdf.py", line 22
>     print(*args, file=sys.stderr)
>           ^
> SyntaxError: invalid syntax

**Comment by leres** [comment]
> @leres Thanks, I tried to run your script but it's throwing an error:
> 
> > File "./convert-rdf.py", line 22
> > print(*args, file=sys.stderr)
> > ^
> > SyntaxError: invalid syntax

I just made a change to add python 2 compatibly, could you please get the new version and try again?

**Comment by designchris** [comment]
Thank you! At first it failed on Windows, but it works great on Linux!

**Comment by htgoebel** [comment]
I confirm this pull-request makes tb-correctidentity work on Thunderbird 68.0

**Comment by pbonbon** [comment]
Plugin doesn't work correctly on Windows 10 using Thunderbird 68.1.1. The configuration cannot be saved.

**Comment by peci1** [comment]
See https://github.com/bit/tb-correctidentity/pull/1 . I got the fix there and let's hope it will propagate to this PR, too.

**Comment by pbonbon** [comment]
> See [bit#1](https://github.com/bit/tb-correctidentity/pull/1) . I got the fix there and let's hope it will propagate to this PR, too.

It works! Thank you very much!

**Comment by bertvandepoel** [comment]
@bit I just pulled from your repo and zipped the tb68 branch, then zipped the result. Weirdly, Thunderbird keeps on saying that it's incompatible with 68.4.1. Any guess what I'm doing wrong? Thx :)

**Comment by SimonMaenaut** [comment]
Sadly the following error appears when I try to install this extension in Thunderbird 68.5.0 on Linux.
`addons.xpi	WARN	Invalid XPI: Error: File /home/simon/Downloads/tb-correctidentity-tb68.zip does not contain a valid manifest(resource://gre/modules/addons/XPIInstall.jsm:671:11) JS Stack trace: loadManifest@XPIInstall.jsm:671:11
`

**Comment by SimonMaenaut** [comment]
Zipping the individual elements together instead of a directory with everything inside seems to do the trick :-)

**Comment by bertvandepoel** [comment]
It seems to install fine with the instructions by @SimonMaenaut but the addon doesn't work for me at that point. I then went on to explore and found that https://github.com/rwg0/tb-correctidentity/tree/tb68 by @rwg0 had a fix for problems with fetching identities (which I seemed to have) and also merged in another fix by @peci1 for saving of settings.
Could you contemplate merging those, @bit , and then adding them to this PR? Hopefully that will convince @dennisverspuij to merge this PR and release on AMO.

**Pull request closed without merging**
