### PR TITLE
Thunderbird 78.x code

### PR DESCRIPTION
**Pull request by ldreier**
Hi Dennis,

I tried to convert your "correct identity" add-on to the new webextension / mailextension format.
I uploaded the result to my branch.
I personally only used a small featureset of the add-on. I tried to also understand the other functions and try to convert them also.

From the architecture I see the difference, that we are now not hooked into the opening of a compose window. I use
a 1-second polling mechanism to discover new compose windows and to detect changes to recipients and/or sender identities.
With this I am not getting any "reply-hints", so I skipped the replyFromRecipient feature.

Please have a look.
It would be ok for me, if you adopt the code and publish it as a new version of your add-on.
You can also do some testing an comment on bugs and features.

Regards,

Ludger

### CODE REVIEW

**Comment by dennisverspuij** [comment]
Hi Ludger, thanks very much for your message and efforts!
You probably noticed I haven't touched this addon in a couple of years, and barely took time to respond to the various issues and proposed fixes. Also because of the extensive architectural changes of Thunderbird and addon development over time, which I do not have time and feel the urge to actually dive in to. So I am happy you did, and may be you would like to take the lead and let me add you as collaborator in this repository, instead of me testing and merging changes?
I do must say I created the addon for the exact thing you say you can't implement, that is reply from the identity the mail was sent to. Without that feature I do not think most users would consider this an upgrade. But per haps it is [already present in the core](https://github.com/absorb-it/Virtual-Identity/issues/22#issuecomment-689357184)? I don't know (not using TB 78 atm). However, may be you can investigate further if this feature can be retained, hook differently without the need for polling for windows, etcetera?
Hop to hear from you, thanks again!

**Comment by ldreier** [comment]
Hi Dennis,

> may be you would like to take the lead and let me add you as collaborator in this repository

I think in general that could be a way forward. I will also not spent too much time in this project,
but supporting that code should be possible with some limited effort.

> ... But perhaps it is already present in the core?
(re feature "replyFromRecipient")
I think this is already "in" in Thunderbird. I my tests, the alias used
in "to" is also chosen in the reply. But maybe this is specific to my
setup/configuration.

Maybe something worth to note:
    - The new code uses also a new preference storage ("storage.sync")
      Currently no effort was undertaken to migrate existing preference settings
      to the new version. Maybe we should also add this to the "todo-list"
      
Regarding next steps:
 - I will continue to do some testing
 
 - I will also have look on some improvements
    - check for replyFromRecipient implementation possibilities
    - try to get around a focus/cursor jump, when identity is changed. (E.g. when
      you "enter" a recepient by changing to the subject line, your cursor
      jumps back to the "to" line after the automatic identity change.
      Seems to be a feature of the main Thunderbird code
    - get away from polling
    - look into preferences migration
 
 - When should we put that code into your repo?
    - required level of testing
    - which of the improvements are mandatory?
    - Will every commit to the repo will get a new tag/version?
 
 - When and how should new versions be released to addons.thunderbird.net?
    - should this be published as a new versions of the existing add-on?
    - Will every new repo tag be published as an add-on?
    - We need to crosscheck the manifest.json entries (version, author, id) before upload

Regards,

Ludger

**Comment by alexolog** [comment]
I find "X-Delivered-to" to be much more useful than "To"

Is it possible to support it?

**Comment by dennisverspuij** [comment]
@ldreier

Sounds great. I will be very happy to test, just let me know when you want.

It may be wise to keep your commits in a new branch, then when you finished up a version for release I can merge it into master at once. I will then tag it as new version, and manually package and upload it to the TB addons portal.

I just installed tb 78.5.0 and concluded it picks identities for replies exactly like earlier versions did, and why I created the addon: it will only pick an identity from the account the message is stored in. So yes I would prefer this addon to continue offering users these options for TB78:
1. change the identity to be used when composing a new message from an account (which may very well be an identity from another account)
2. for replies pick an identity best matching the incoming email address regardless of where the message is stored (reply identity picking mechanism)
3. allow accounts to be excluded from the reply identity picking mechanism
4. allow identities to be excluded from the reply identity picking mechanism
5. support identity aliases (alternate addresses, sender names, domains, etc., as either substrings or regular expressions), that will have the identity selected when matching incoming address, as well as any outgoing email addresses (on-the-fly!)
6. migrating options from pre-78 versions is not a must-have for me, I think users will be glad enough to see the addon available again.

Regarding 5. I noticed TB 78 offers a similar option "Reply from this identity when delivery headers match"., but again it seems to work on messages stored within the account only. Furthermore it supports wildcards but not regexps, and the patterns are not matched on outgoing addresses. So I guess most users would love to see 5. being retained.

**Comment by dennisverspuij** [comment]
> I find "X-Delivered-to" to be much more useful than "To"
> 
> Is it possible to support it?

The extraction and precedence of email addresses from relevant headers for the identity selection is done by TB, not the addon. I recall it scans To, Reply-To, Envelope-To, etc., per haps current version also scans X-Delivered-To, I don't know, you may be able to find out from the source code.

**Comment by pbonbon** [comment]
You saved my life :-) Thanks for plugin update.

**Comment by leres** [comment]
I just submitted a [pull request](https://github.com/ldreier/tb-correctidentity/pull/1) against the ldreier fork, I wasn't able to actually send messages because I have some safety addresses set which revealed an uninitialized variable; the composition window would just hang after pressing "send".

It's great to have this plugin working with 78.X! I'm using it with FreeBSD (!), Windows 10, and OSX.

**Comment by ldreier** [comment]
@dennisverspuij 

So after doing some additional testing also with the current Thunderbird Beta version, my personal list of open points is now empty...
This includes also your item list from approx. 3 weeks ago. So the requested functionality should now be available.

Most of the missing things were implemented using Thunderbirds "Experiments API" feature.

So please have a look and do some testing...

**Comment by dennisverspuij** [comment]
@ldreier Awesome work, almost there! My TB 78.6.0 correctly changes identities based on the configuration and the email recipients replied for most of the times. I found only these few unexpected edge cases where the addon did not change identity as expected:
- imho an address match should have precedence over an alias/regexp match, e.g. when I reply a mail sent to me@me.com it should always take that exact identity if it exists regardless of having me.com as alias/regexp in any of the other identities
- change identity as-you-type works very nice and similar, except it does not revert to the initial identity when no aliases match anymore (when you remove a recipient that triggered identityt switch before)
- I have multiple messages in account A sent to (To:, Envelope-To and Delivered-To) identity X of account B, but for one of them it fails to switch to X. When I move the message to B it does detect and switch to X upon replying, move back and it doesn't. Very weird, I have yet to figure out why this happens for this message. Did you experience this yourself sometime? Any help on how to debug this, e.g. mention identity hint in console?
- using TB 78,.5.0 didn't work, I did remove startup cache etc, any ideas why?

Thanks!

**Comment by ldreier** [comment]
@dennisverspuij 
After looking into your 4 points from 23. December, I did some changes...
Please have a look to the commit message.
Notes regarding your 4 points:
1. When doing some tests to reproduce this, I found some problems around settings and the option GUI. Here I did some changes. Actually the precedence sequence / priorities regarding this point seemed to be already OK. The "explicitIdentity" was moved up in the priority.
2. Here I changed the code so that the initial identity is now always used as a starting point (e.g. to get the account settings). The replyHint is also now always used an not only when opening the compose window. So the resulting identity should now be "deterministic" and not depend on the sequence of actions.
3. Here I have also no idea. I left some console.log() calls in the "getIdentitiy()" function to allow further analyzing
4. The TB 78.5.0 problem seem to be https://bugzilla.mozilla.org/show_bug.cgi?id=1675012

**Comment by dennisverspuij** [comment]
Hi, thanks for the updates and adding debug info, Regarding my issue I see that for some newsletter messages the TB provided the replyHint is empty, even though To, Delivered-To and Envelope-To all contain same valid identity email address. The TB default mechism (addon disabled) however does select the identity when the message is within the account of X. Probably it has access to other information than the replyHint only, Any idea why the hint may become empty? I can't seem to find any [TB issue](https://bugzilla.mozilla.org/buglist.cgi?classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&chfield=%5BBug%20creation%5D&resolution=---&short_desc_type=allwordssubstr&component=Message%20Compose%20Window&short_desc=identity&query_format=advanced&product=Thunderbird&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED) related to this.
Besides this I think the update is good to go, could you provide/add your name, so you can take the credits?

**Comment by leres** [comment]
I think the current version (33e8913) breaks thunderbird templates; with the add-on enabled if I double-click on a message in my Templates folder it opens a draft as usual but the To field is empty; disabling the add-on allows the creation of a draft from a template to work as expected.

I also have a template that uses both to and reply-to and both fields are unpopulated with the add-on enabled.

**Comment by leres** [comment]
> ... with the add-on enabled if I double-click on a message in my Templates folder it opens a draft as usual but the To field is empty

I just noticed that  right-click "Edit As New Message" also suffers from this issue.

**Comment by leres** [comment]
I've seen another issue with 33e8913 related to safety identities. Let's say I have two accounts, leres@example.com and leres@example.org and leres@example.com has test@example.com as a safety identity and @example.com as a detection domain. If I attempt to send a message from leres@example.com to test@example.com, I correctly receive a popup warning me about test@example.com. But if I select leres@example.org for the From field and then enter test@example.com in the to field, the add-on changes the from to leres@example.com (so far so good). If I then manually change it back to leres@example.org and press send, there is no popup and leres@example.org is the from address when the message is delivered.

I think what's happening is the safety check is using the from address that correct-identity would have picked instead of the from address that was actually used?

**Comment by htgoebel** [comment]
Testing 33e8913, I discovered this error: When answering to a mailing-list, the "From" address will be set to the mailing-list's address. Near the bottom of the message-compose window there is a warning (translated from German)
> No Identity found matching the From-Field. Msg will bes send using the current address of the From-Field and the setting of Identity "Real name <real\@name>"

(The named identity is the one which should be selected for this mailing list.)

**Comment by ldreier** [comment]
@dennisverspuij
Re: "... replyHint is empty".
In general I used the method from "[getIdentityForHeader](https://searchfox.org/comm-central/rev/e17307c52ba870bc37f68829e713242b7d9c5879/mail/base/modules/MailUtils.jsm#485)" in [ext-api.js](https://github.com/ldreier/tb-correctidentity/blob/33e8913a3b4328085accec852b748c17154ac9cb/scripts/exp_api.js#L54).

Re: name
The full name is "Ludger Dreier".

I will now look into the comments after yours. Maybe this will result in further changes...

**Comment by ldreier** [comment]
@leres (Re: Empty "To" field)
This seems to be caused by calling messenger.compose.getComposeDetails directly in onTabCreated().
Feels like a concurrency problem in Thunderbird itself. Somehow "To", "CC" stay empty in this case. Recently there was a change in the Thunderbird code in this area:
https://bugzilla.mozilla.org/show_bug.cgi?id=1675012
A workaround would be a delay before calling getComposeDetails. In my tests 30ms were enough...
I will think about a better solution...

**Comment by ldreier** [comment]
@leres, @htgoebel
The change 001428a should address the empty "to" issue and both HTML related comments. (see commit message).

For the "example.com" issue of Craig, I think it "behaves as intended". But maybe I was confused by the test description...
So you write "there is no popup and leres@example.org is the from address when the message is delivered". But above that you state "leres@example.com has test@example.com as a safety identity". So I think it should only warn if you send from "leres@example.com"?

**Comment by peci1** [comment]
I've tried this PR version and it works for me. Any intentions to make an official release?

**Comment by alexolog** [comment]
@ldreier does the add-on (with your changes) work with TB91 and up?

**Comment by alexolog** [comment]
> "strict_max_version": "91.*"

@ldreier Maybe allow versions above 91?
See https://en.wikipedia.org/wiki/History_of_Mozilla_Thunderbird#cite_ref-406

**Comment by ldreier** [comment]
@alexolog 
> Maybe allow versions above 91?

Seems not. I tried e.g. "999.*" "99.*" and "92.*". All were rejected by the add-on checker when trying to upload it.

**Comment by alexolog** [comment]
> @alexolog
> 
> > Maybe allow versions above 91?
> 
> Seems not. I tried e.g. "999._" "99._" and "92.*". All were rejected by the add-on checker when trying to upload it.

Strange.  Other add-ons on AMO accept higher version numbers

For example:
```
{
  "manifest_version": 2,
  "name": "__MSG_extensionName__",
  "description": "__MSG_extensionDescription__",
  "version": "91.0.2",
  "author": "Philipp Kewisch",
  "homepage_url": "https://addons.thunderbird.net/thunderbird/addon/provider-for-google-calendar/",
  "default_locale": "en",
  "applications": {
    "gecko": {
      "id": "{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}",
      "strict_min_version": "91.0",
      "strict_max_version": "102.0"
    }
  },
...
}
```

**Comment by peci1** [comment]
That's only a limitation for addons using experimental APIs. gcal provider probably uses none.

**Comment by ldreier** [comment]
This upload-limitation seems to be made more restrictive recently.
I tried - as a test - to upload the extension @alexolog mentioned. Error:
    **Unknown "strict_max_version" 102.0 for Firefox**
Those errors also point to https://github.com/thundernest/addons-server as a reference. But here the last change was made on August 31st.
If you like to directly download the .xpi from github, I added a "_dev" version without the strict_max_version entry.
E.g. https://github.com/dennisverspuij/tb-correctidentity/releases/download/v2.0.1/correct_identity_v2.0.1_dev.xpi

**Pull request merged**
